import { dressCurrentStatusValues } from "@/drizzle/schemas/system/dresses-table";

import { DEFAULT_IMPORT_BATCH_SIZE, type ImportEntitySpec } from "./types";

/**
 * Column specs mirror the Drizzle tables: a column is `required` exactly when
 * its database column is NOT NULL without a default. Audit columns
 * (`createdBy`, timestamps) are never template columns — the importer fills
 * them from the acting session.
 */

export const branchesImportSpec: ImportEntitySpec = {
  slug: "branches",
  kind: "master",
  titleKey: "systemPages.branchesTitle",
  // Branch CRUD is admin-only in branches/server/mutations.ts; import must match.
  requiredRole: "admin",
  dependsOn: [],
  naturalKey: ["shortCode"],
  branchScoped: false,
  batchSize: DEFAULT_IMPORT_BATCH_SIZE,
  columns: [
    {
      key: "shortCode",
      labelKey: "systemPages.importColumnShortCode",
      required: true,
      type: "string",
      maxLength: 8,
      aliases: ["short_code", "code", "branchcode", "branch_code"],
      exampleValue: "MAADI",
      helpKey: "systemPages.importHelpShortCode",
    },
    {
      key: "nameEn",
      labelKey: "systemPages.importColumnNameEn",
      required: true,
      type: "string",
      maxLength: 128,
      aliases: ["name_en", "name", "englishname"],
      exampleValue: "Maadi Branch",
    },
    {
      key: "nameAr",
      labelKey: "systemPages.importColumnNameAr",
      required: true,
      type: "string",
      maxLength: 128,
      aliases: ["name_ar", "arabicname"],
      exampleValue: "فرع المعادي",
    },
    {
      key: "addressEn",
      labelKey: "systemPages.importColumnAddressEn",
      required: false,
      type: "string",
      aliases: ["address_en", "address"],
      exampleValue: "12 Road 9, Maadi",
    },
    {
      key: "addressAr",
      labelKey: "systemPages.importColumnAddressAr",
      required: false,
      type: "string",
      aliases: ["address_ar"],
      exampleValue: "١٢ شارع ٩، المعادي",
    },
    {
      key: "phone",
      labelKey: "systemPages.importColumnPhone",
      required: false,
      type: "string",
      maxLength: 32,
      aliases: ["telephone", "mobile"],
      exampleValue: "+20 2 2358 1234",
    },
  ],
};

export const employeesImportSpec: ImportEntitySpec = {
  slug: "employees",
  kind: "master",
  titleKey: "systemPages.employeesTitle",
  dependsOn: ["branches"],
  naturalKey: ["email"],
  branchScoped: false,
  batchSize: DEFAULT_IMPORT_BATCH_SIZE,
  columns: [
    {
      key: "email",
      labelKey: "dataTable.columnEmail",
      required: true,
      type: "string",
      maxLength: 256,
      aliases: ["e-mail", "emailaddress", "email_address"],
      exampleValue: "sara@atelier.example",
      helpKey: "systemPages.importHelpEmailKey",
    },
    {
      key: "name",
      labelKey: "forms.name",
      required: false,
      type: "string",
      maxLength: 256,
      aliases: ["fullname", "full_name", "employeename"],
      exampleValue: "Sara Ahmed",
    },
    {
      key: "phone",
      labelKey: "dataTable.phone",
      required: false,
      type: "string",
      maxLength: 16,
      aliases: ["mobile", "telephone"],
      exampleValue: "01001234567",
    },
    {
      key: "age",
      labelKey: "forms.age",
      required: false,
      type: "int",
      exampleValue: "29",
    },
    {
      key: "branchShortCode",
      labelKey: "systemPages.importColumnBranchShortCode",
      required: false,
      type: "ref",
      ref: { entity: "branches", lookupBy: "shortCode" },
      aliases: ["branch", "branchcode", "branch_code", "branch_short_code"],
      exampleValue: "MAADI",
      helpKey: "systemPages.importHelpBranchAssignment",
    },
  ],
};

export const customersImportSpec: ImportEntitySpec = {
  slug: "customers",
  kind: "master",
  titleKey: "systemPages.customersTitle",
  dependsOn: [],
  // Customers are tenant-wide and deduped on phone, matching the unique index
  // on rental_customers.phone.
  naturalKey: ["phone"],
  branchScoped: false,
  batchSize: DEFAULT_IMPORT_BATCH_SIZE,
  columns: [
    {
      key: "phone",
      labelKey: "dataTable.phone",
      required: true,
      type: "string",
      aliases: ["mobile", "telephone", "phonenumber", "phone_number"],
      exampleValue: "01001234567",
      helpKey: "systemPages.importHelpPhoneKey",
    },
    {
      key: "name",
      labelKey: "forms.name",
      required: true,
      type: "string",
      aliases: ["fullname", "full_name", "customername", "customer_name"],
      exampleValue: "Nour Hassan",
    },
    {
      key: "note",
      labelKey: "systemPages.importColumnNote",
      required: false,
      type: "string",
      aliases: ["notes", "comment", "remarks"],
      exampleValue: "Prefers evening pickups",
    },
  ],
};

export const dressesImportSpec: ImportEntitySpec = {
  slug: "dresses",
  kind: "master",
  titleKey: "systemPages.dressesTitle",
  dependsOn: ["branches"],
  // dresses.code is globally unique, not per-branch.
  naturalKey: ["code"],
  branchScoped: true,
  batchSize: DEFAULT_IMPORT_BATCH_SIZE,
  columns: [
    {
      key: "code",
      labelKey: "systemPages.dressesCode",
      required: true,
      type: "string",
      maxLength: 128,
      aliases: ["dresscode", "dress_code", "sku", "reference"],
      exampleValue: "DR-0001",
      helpKey: "systemPages.importHelpDressCodeKey",
    },
    {
      key: "title",
      labelKey: "systemPages.dressesTitleCol",
      required: true,
      type: "string",
      maxLength: 255,
      aliases: ["name", "dressname", "dress_name"],
      exampleValue: "Ivory A-Line Gown",
    },
    {
      key: "pricePerDay",
      labelKey: "systemPages.dressesPricePerDay",
      required: true,
      type: "money",
      aliases: ["price", "price_per_day", "dailyprice", "rentalprice"],
      exampleValue: "1500",
    },
    {
      key: "depositAmount",
      labelKey: "systemPages.dressesDeposit",
      required: true,
      type: "money",
      aliases: ["deposit", "deposit_amount"],
      exampleValue: "500",
    },
    {
      key: "insurance",
      labelKey: "systemPages.dressesInsurance",
      required: true,
      type: "money",
      aliases: ["insurance_amount"],
      exampleValue: "300",
    },
    {
      key: "branchShortCode",
      labelKey: "systemPages.importColumnBranchShortCode",
      required: false,
      type: "ref",
      ref: { entity: "branches", lookupBy: "shortCode" },
      aliases: ["branch", "branchcode", "branch_code", "branch_short_code"],
      exampleValue: "MAADI",
      helpKey: "systemPages.importHelpBranchFallback",
    },
    {
      key: "description",
      labelKey: "systemPages.dressesDescription",
      required: false,
      type: "string",
      aliases: ["details", "notes"],
      exampleValue: "Silk crepe, sweetheart neckline",
    },
    {
      key: "size",
      labelKey: "systemPages.dressesSize",
      required: false,
      type: "string",
      maxLength: 64,
      exampleValue: "M",
    },
    {
      key: "color",
      labelKey: "systemPages.dressesColor",
      required: false,
      type: "string",
      maxLength: 64,
      exampleValue: "Ivory",
    },
    {
      key: "isActive",
      labelKey: "systemPages.importColumnIsActive",
      required: false,
      type: "boolean",
      aliases: ["active", "enabled"],
      exampleValue: "true",
      helpKey: "systemPages.importHelpBoolean",
    },
    {
      key: "currentStatus",
      labelKey: "systemPages.dressesStatus",
      required: false,
      type: "enum",
      enumValues: dressCurrentStatusValues,
      aliases: ["status"],
      exampleValue: "available",
    },
  ],
};
