/**
 * Prints the CSV contract the importer accepts, generated from the specs in
 * `src/features/system/import/specs` so it cannot drift from the code.
 *
 *   npm run import:contract > docs/import-contract.md
 *
 * Exists for the export side living in another repository: whoever writes the
 * exporter needs the exact headers, accepted value formats and matching keys,
 * and a hand-maintained copy of that would go stale the first time a spec
 * changes.
 */

import type { ImportColumnSpec } from "@/features/system/import/specs";
import { IMPORT_SPECS } from "@/features/system/import/specs";

const TYPE_HELP: Record<string, string> = {
  string: "text",
  int: "whole number",
  money: "whole number (no decimals, no currency symbol)",
  date: "YYYY-MM-DD",
  datetime: "YYYY-MM-DD HH:mm",
  boolean: "true/false, yes/no or 1/0",
  enum: "one of the listed values",
  ref: "natural key of another record",
};

function describe(column: ImportColumnSpec): string {
  if (column.type === "enum") {
    return `one of: ${(column.enumValues ?? []).join(", ")}`;
  }
  if (column.type === "ref" && column.ref) {
    return `${column.ref.entity} matched by \`${column.ref.lookupBy}\``;
  }
  const base = TYPE_HELP[column.type] ?? column.type;
  return column.maxLength ? `${base}, max ${column.maxLength} chars` : base;
}

function main() {
  const lines: string[] = [];

  lines.push("# Import CSV contract");
  lines.push("");
  lines.push(
    "Generated by `npm run import:contract` — do not edit by hand. Re-run it after changing any import spec.",
  );
  lines.push("");
  lines.push("## Rules that apply to every file");
  lines.push("");
  lines.push("- UTF-8, comma separated, one header row.");
  lines.push(
    "- Header matching ignores case, spaces, underscores and hyphens, and accepts the aliases listed per column — an existing export often needs no renaming.",
  );
  lines.push(
    "- Unrecognised columns are reported back to the admin and ignored, never rejected.",
  );
  lines.push(
    "- Empty optional cells are fine; empty required cells fail the row.",
  );
  lines.push(
    "- Money and other amounts are whole numbers. `1500.50` fails rather than being rounded.",
  );
  lines.push(
    '- Quote any cell containing a comma, quote or line break, doubling inner quotes (`"a ""b"", c"`). Line breaks inside quoted cells are handled.',
  );
  lines.push("- Max 4 MB per file, max 100,000 rows.");
  lines.push("");
  lines.push("## Import order");
  lines.push("");
  lines.push(
    "Each entity's references must already exist, so export and import in this order:",
  );
  lines.push("");
  for (const [index, spec] of IMPORT_SPECS.entries()) {
    const deps =
      spec.dependsOn.length > 0
        ? ` (needs ${spec.dependsOn.join(", ")})`
        : " (no dependencies)";
    lines.push(`${index + 1}. **${spec.slug}**${deps}`);
  }
  lines.push("");

  for (const spec of IMPORT_SPECS) {
    lines.push(`## ${spec.slug}`);
    lines.push("");
    lines.push(
      `Existing records are matched on **${spec.naturalKey.join(" + ")}** — a row whose key already exists updates that record instead of creating a duplicate. A key repeated inside one file fails both rows.`,
    );
    if (spec.branchScoped) {
      lines.push("");
      lines.push(
        "Branch-scoped: a row may name its branch, otherwise the branch chosen in the import dialog is used.",
      );
    }
    lines.push("");
    lines.push("| Column | Required | Accepts | Also accepted as | Example |");
    lines.push("| --- | --- | --- | --- | --- |");

    const ordered = [...spec.columns].sort((a, b) =>
      a.required === b.required ? 0 : a.required ? -1 : 1,
    );

    for (const column of ordered) {
      const aliases = (column.aliases ?? []).map((a) => `\`${a}\``).join(", ");
      lines.push(
        `| \`${column.key}\` | ${column.required ? "**yes**" : "no"} | ${describe(column)} | ${aliases || "—"} | ${column.exampleValue} |`,
      );
    }

    lines.push("");
    lines.push("Header row:");
    lines.push("");
    lines.push("```csv");
    lines.push(spec.columns.map((column) => column.key).join(","));
    lines.push("```");
    lines.push("");
  }

  console.log(lines.join("\n"));
}

main();
